"""empty message

Revision ID: 0382fd21fabb
Revises: e0476e592dde
Create Date: 2021-04-20 00:20:36.719123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0382fd21fabb'
down_revision = 'e0476e592dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('poeple_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'people', ['poeple_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'poeple_id')
    # ### end Alembic commands ###
