"""empty message

Revision ID: 235d536fd08b
Revises: 1330194e1d9b
Create Date: 2021-04-17 23:30:08.953424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '235d536fd08b'
down_revision = '1330194e1d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.drop_index('person', table_name='favorites')
    op.drop_index('planet', table_name='favorites')
    op.create_foreign_key(None, 'favorites', 'planets', ['planet_id'], ['id'])
    op.drop_column('favorites', 'planet')
    op.drop_column('favorites', 'person')
    op.drop_column('favorites', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('name', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('favorites', sa.Column('person', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('planet', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_index('planet', 'favorites', ['planet'], unique=True)
    op.create_index('person', 'favorites', ['person'], unique=True)
    op.drop_column('favorites', 'planet_id')
    # ### end Alembic commands ###
