"""empty message

Revision ID: 4377a75d56b5
Revises: 0382fd21fabb
Create Date: 2021-04-22 01:05:27.444926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4377a75d56b5'
down_revision = '0382fd21fabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('people_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_ibfk_3', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'people', ['people_id'], ['id'])
    op.drop_column('favorites', 'poeple_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('poeple_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_ibfk_3', 'favorites', 'people', ['poeple_id'], ['id'])
    op.drop_column('favorites', 'people_id')
    # ### end Alembic commands ###
